### ISSUE TITLE
Create what we offer section and also make it responsive

### ISSUE THREAD

**Issue by Glory135** [gray-adeyi/orderlie-fe-react#13]
I wan to work on the home page

**Comment by Elijah699** [comment]
@Glory135  Can you share a screenshot of where you want to work on please?

**Comment by Glory135** [comment]
![Ordelie-–-Figma](https://github.com/gray-adeyi/orderlie-fe-react/assets/79275377/cc8593a2-599c-48ff-9645-e80e57683800)

**Comment by Elijah699** [comment]
@Glory135 Kindly work on the what we offer section and Ready to try different work experience section also make it responsive.

Kindly acknowledge you have seen this message @Glory135.

**Comment by Glory135** [comment]
Okay

**Comment by Elijah699** [comment]
Solved #16
