### ISSUE TITLE
DESIGN: Create a design for the Orderlie Home Page

### ISSUE THREAD

**Issue by Elijah699** [gray-adeyi/orderlie-fe-react#20]

**Comment by vidhan63-soe** [comment]
Assign this to me , and what is the deadline for this?

**Comment by Elijah699** [comment]
@vidhan63-soe This screen has been assigned to someone already.

**Comment by vidhan63-soe** [comment]
That is good. Do you any discord or server , i am facing problem during setup.

**Comment by Elijah699** [comment]
@vidhan63-soe  You can join the Hacktoberfest discord server via hacktoberfest.com

**Comment by Gabrielv9** [comment]
I'll love to work on this.

**Comment by Elijah699** [comment]
solved #19
