### ISSUE TITLE
Work on the "Upload Biodata" Of The Design

### ISSUE THREAD

**Issue by devchaos0** [gray-adeyi/orderlie-fe-react#45]

**Comment by DanielAgbeni** [comment]
Pls can I work on this?

**Comment by devchaos0** [comment]
@DanielAgbeni You Can Work on This

**Comment by wonderful-coyote** [comment]
hello can i work on this...? but no description was added

**Comment by devchaos0** [comment]
@wonderful-coyote someone else is already working on this...

**Comment by wonderful-coyote** [comment]
@Chaos10001 noted... thanks

**Comment by DanielAgbeni** [comment]
Done 
#58 
![image](https://github.com/gray-adeyi/orderlie-fe-react/assets/99095841/8aad1307-59f4-4471-b89a-5561a5ac1452)
![image](https://github.com/gray-adeyi/orderlie-fe-react/assets/99095841/411cf492-6484-469c-b680-6d4df1e0678a)

**Comment by devchaos0** [comment]
@DanielAgbeni Your Contribution has been Merged
